= monorepo for cppfw libraries

**cppfw** libraries repositories are added as submodules under the `repos/` directory.
The submodules are configured to `latest` remote branch. So updating the submodules with:
```
git submodule update --remote --init
```
Will always sync to latest release versions of the libraries.

== Building with CMake

=== Prerequisites

- link:https://vcpkg.io[VCPKG] installed and `VCPKG_ROOT` environment variable set accordingly
- **Linux:** `pkg-config`, `zip`, `libgl1-mesa-dev`, `libgtk-3-dev` installed
+
```
sudo apt install pkg-config zip libgl1-mesa-dev libgtk-3-dev
```

=== Building

```
mkdir out
cd out
cmake ../build/cmake
cmake --build . --parallel
```

Test applications binaries will be put to `out/exe` directory.

=== Building on Windows

On Windows one can use the provided command scripts:

* `msvc2022_gen.cmd` - fetches submodules, installs vcpkg and generates Microsoft Visual Studio 2022 project
* `msvc2022_build.cmd` - generates Microsoft Visual Studio 2022 project and builds Release target
* `msvc2022_open.cmd` - generates Microsoft Visual Studio 2022 and opens it in the IDE

=== Adding your own projects

You can create your own applications inside `apps` subdirectory. Make sure to have your CMakeLists.txt inside
`apps/<your_app_name>/build/cmake` directory and build scripts will add it to the project automatically.
